sudo: required
language: java
install: true
jdk: oraclejdk8

services:
  - docker

before_script: cd app

script:
  - "./gradlew clean pushDockerImage"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

deploy:
  provider: heroku
  app: spring-boot-docker-k8s
  api_key:
    secure: "jbOKAkjiehR8qzLve4lvrZBfrjA/k3a7gR4dGYFw/4xMkGX1YZonI3zTE0uGcOuHyjm0FQaVa0gzKsieRQu2cyL8eiOWXRPmSDgb8wHyjPLxbwh+GP2h/GbOOvhiDOvYpfrrqQMztjs6ea/uPMWlTfnOBlCKanT0RRpo0LtJmJf0qU4dlhz05nI87YVij1ICQzrndrh3m/FES59o8U7vg+LfK2gFGPxBroD5FTFFw3vAjp1KsiKgW5j5tE+DyndB0wk/ZE/72O/d+JxcWs77hRHcn89tedbMiJyocwbSnsb7qAOb+8E1lV/aoZktzyxRWuRQVn9tk8IaMIiBFFUQmfnJ/WcwzN2wrol4G5ehthHDf0lqoxvp5yqxsnUl237dXln6+VersCJorr8650/ZE0RXdUAsI7e6j87hwdXiX0f21Stv+aEYR2Ad2BGa/J+uNJfNOL3E5nQsYYZ5nzTv00vCq3CT5OGy7AbwIb/UoGbTUdEOOWBrx7JYWA/yCvSHw/03Vnuq2qXJWWhY6OPiBOrPX5JMix5dZgplNmiCZukce9zKoVB1RQDeZ4xMTZo1vW5L3cHyn1z9qV0Z/i2vlTgXj1TyP86i3ZUY4bPuL2YpHfXIvbk76lsaqKTRhcPNA3lMH7237hhskypRisxVyX9AtCbnatHNKTXUXZExmY0="

env:
  global:
  - secure: Y11dNCTXTLpu17Gav0jLjg5PQfHMR1qtUWzW+75F52n17EDRtcGsYK2QDeum3tKd0EZEtgQEQ2Op7IDYxq5l0YVfhiee2KqUb2QD2u7b03F7ndlytdp85C2zwAp3oTU6PPq66oQq9b1/xV+Ebur2Ex1Igv9A7UVeUkvjgfEq+G3n36nds/pA43y5DvNAx7vev2FSUa59faZEVlE9QHx+X9HmPNmLKvnhI0a+ewQ2KOv20sYFOuI/xRIn5DCLCYCiXNA+xImHP/DCuJuISp8OuuuDYjnRX6uTyxigPok/BXwmAIXj+2hlzZ7r40LzFYw/o2BVdDNyP8o+lISMvJNRNB7hZ0Cs0kyLpoZ7rKT5J50iBuPftt4AcrupXxj0yTST4/or1fzuKWTpTwsckXZ9UCqExuQvdAI0PPoAiE7ektvMnAn3b1oEs7D5aVzr3HwWaOnT+Wj0qMkoMkvcf82n74GCvvrkEQ/FJW8c6qfoNqnnBjxDYHWNQDiKmOKE4+TA4KkE8fEwQXn9wvgl/EFaunvyoX713k/tkTPNlQqfv8DZoheGxGC6w9ST4w/4LNUZiHqTXs3LLz/tliDNp2leWO23nQx0xW2ARg+CGBEFljjyrpCLUw/Sldmp5SXdUJAi2vAqTyI5Ozn0MA/COc3nMGZIO36fiaRPam7/NeAxVcw=
  - secure: E5P7hju5y7badYSge/ud7riGZ/Hm7hNWcJPZtzVm/hiFUFum0ts1NY9Tbrfxoef5HyElmxIJG1hfBcFpzH7D/6AztEz/4oz1+GjD1PJxOgu26YJVbMjs+4Zv14sRfL2eKN38lDWIDo3dl/XhxzaGX3G7dEx4rupMnN9Y21tNOvS6nRAr/JXQA5Z6KMqFPVIb2ljIedfPhlhE+CYbofrLt5WPIhRjqYQp6krkWNOOJ0Jb9NWqxMhpQzd4PDjBthKYxcpmLFN77eq2hvs9tMwIpyTqL0YqSRqUe+zbv2dNv0dhabc4PUTf+YELRmFQ7HIAJXD8rkBQd9Hm9IXQc7NvQ4D1jUo2RZJBMAjN8pxNkSCZNgrcaUKxvAWrLcy4SmjAUgrSsX2hyNGa1KvA7IbKqEiN0k031scLs+cZa5kwdChsLTCKtezaQCIV4LxGvRhnqRlDRsM+T1ubDbOgxVcEoirSVbqEKSS4kcR59b/UOdr6hzja/4a/avrOgNM+AS7KjMG/L+MtGMCFogZ+jwAJ1sz808RD3osN+tbrkVFP8YsYNb6f52TeQmfEL2lA1DOjflwp9CNK7qDBMW9HrMy85zJVITs49Nu9bFv+SM8VEX+3UyYLwJKzRb6QTQqHEip4ZiyVyXt9nL28axIS5yVuSFiMZifk8AOChBpzPEai60Q=
  - secure: kzBqb4sOdWMrNN+czi1P+kyWS9cv8yyOuCBB/q7vCHC+woBr/vKh/7nuhT5zCISlGf3HZo8oW4nfmYnBnsPUJalh2bKw5GQqetBmvOHB8r1KBSph/vHnNZCSWgW8LvUnezZDzI/ucLa/Q1Iwu95NM/14eY5IgFW+s6Auyrpulb7RmWcqcbv3UK9mgUpjHwWlC9gOFOm2YO0d0GtknAPLkV43pnIPV2hzRml8q0CI7nb2DyoOBfaFaPSwmAZV49PS7NbtLDLCscpde/R6CjStaVrtEPbX04u91yxlAfC1tPFeaqayFPMn6OqO3b805C28gYH97Ie+L2v8jCrTWq7DR4Cpjxza2OXwzZBpvql+vKnpzfgB1I1N0qP7yQi2HaFbdNAwB1WbNjHANQ/TXt0+fOgiNqK9bY6mO8BIL1unR4bB8POoBda1lTHPnppk5rYPTug0eD/dHEk60YaNz6Ulp1iNeQsazRlI6ImME1tmeXI/aEEvCyPiJ4gjFRStZflLp1u/IOHPZnetkw2F37R9mULu30/SptNGLyfi0KWYOrwB4LougPRNOqDVAfJ4TlkFGj3ezVLYc077V/BeoTBUN0kg3HDRHW/4yxbtHiEIxc2G+vbg7BT/yZJXsyAzDySdsfDs5LiTieJ/MAhqniRjedEoTmUe2xthKVXlS3vy3FQ=
