apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spring-boot-docker-k8s-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-docker-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-boot-docker-k8s
    spec:
      containers:
      - name: spring-boot-docker-k8s
        image: tatorodrigo/spring-boot-docker-k8s:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
